using Robust.Client;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Network;

namespace Content.Client.UserInterfaces.Screens;

[GenerateTypedNameReferences]
public partial class MainScreen : UIScreen
{
    [Dependency] private readonly IBaseClient _client = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IUserInterfaceManager _userInterface = default!;
    [Dependency] private readonly IClientNetManager _net = default!;

    public MainScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SetAnchorPreset(this, LayoutPreset.Wide);

        this.Content.SetMessage("DDD                          DDD                              DDD\nDDDD\n\n\n\nDDDDDDDDDDD");
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);
    }
}