using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterfaces.Screens;

[GenerateTypedNameReferences, Virtual]
public partial class Viewport : Control
{
    public Viewport()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);
        
        handle.DrawRect(new UIBox2(Vector2.Zero, this.Size), Color.Green, true);
    }
}